CREATE DATABASE IF NOT EXISTS TEST1;
USE TEST1;
CREATE TABLE IF NOT EXISTS TABLE1 (
    FNAME VARCHAR(25),
    LNAME VARCHAR(25),
    AGE INT
);

INSERT INTO TABLE1 (FNAME, LNAME, AGE) VALUES
('ALEXEY', 'PALAS', 14), 
('NIKITA', 'VSEVOLOD', 31), 
('MIKOLA', 'KOPITO', 21);

SELECT FNAME, LNAME, AGE FROM TABLE1;

-- ALLOW ACCESS WITHOUT ANY RESTRICITONS -- 
SET SQL_SAFE_UPDATES = 0;

-- THEN UPDATE WITH RESTRICTIONS --
UPDATE TABLE1
SET AGE = 15
WHERE FNAME = 'ALEXEY';

SELECT * FROM TABLE1;

DROP DATABASE IF EXISTS TEST1;